### ISSUE TITLE
Pale moon javascript fails

### ISSUE THREAD

**Issue by wizgriz** [flarum/core#182]
Unable to test on the latest FF right now but in Pale moon all I get is a blank screen with the message "Something went wrong."

**JS errors:**
[10:16:51.231] SyntaxError: property name href appears more than once in object literal @ http://discuss.flarum.org/assets/forum-R8nKa29CuFQduC2e.js:22953
[10:16:51.232] ReferenceError: System is not defined @ http://discuss.flarum.org/assets/forum-en-VDTC6L96UQagR3Wf.js:1
[10:16:51.234] ReferenceError: System is not defined @ http://discuss.flarum.org/:72

So, this is the perp:
`{ href: "Button PostMeta-permalink", href: permalink }`

But according to this https://bugzilla.mozilla.org/show_bug.cgi?id=1041128, duplicate properties in strict mode should no longer wield the error, so presumably this is a Pale moon only issue which doesn't have that patch (yet). Still, for what purpose is the duplicate property? A fallback?

**Comment by tobscure** [comment]
Fixed.

**Comment by wizgriz** [comment]
Oh, wow, yeah

**Comment by wizgriz** [comment]
@tobscure did you push this to the live forum? I was still getting the same blank screen on Pale Moon which I assumed was caused by the same error. However, checking the console again, there's a different JS error now.

[14:03:00.903] ReferenceError: Promise is not defined @ http://discuss.flarum.org/assets/forum-XUlO1PvhXEwfFmhC.js:1

That's the only thing it's telling me.

**Comment by tobscure** [comment]
Can you see what code it's referring to?

**Comment by wizgriz** [comment]
I can only see the cached js, couldn't find the source here, I don't know if it's part of some package or something. It stops at line 1 on [this](http://discuss.flarum.org/assets/forum-Ey2uXU0NC00ksCkx.js), presumably at any of the "new Promise"s. That's the first and only JS error and all resources load fine. Only thing I can think of is if the Promise class has some JS quirks in its declaration Pale Moon isn't understanding.

I think [this](https://github.com/kriszyp/promised-io) is the library with the class? As required by loader.js. Maybe an issue needs to be filed with them...

**Comment by tobscure** [comment]
Hmm no this is weird. We're using es6-micro-loader, which has a dependency on ES6 Promises *only if* you call System.import – which we don't, we only call System.get. So I'm not sure why it's trying to run the Promise code.

If I put up an unminified version of the script on discuss.flarum.org, can you try it again and let me know which of the `Promise` instances it's referring to?

**Comment by wizgriz** [comment]
Don't you?

```javascript
                  System.import('locale');
                  System.import('tags/main');
                  System.import('likes/main');
                  System.import('subscriptions/main');
                  System.import('sticky/main');
                  System.import('mentions/main');
                  System.import('bbcode/main');
                  System.import('markdown/main');
                  System.import('emoji/main');
                  System.import('lock/main');
```

That's in an inline `<script>` in the html. Sure enough, calling System.import in the console:
```
[11:29:14.986] System.import()
[11:29:14.988] ReferenceError: Promise is not defined
```

Pale Moon might not be able to debug inline scripts and therefore wasn't finding this? Otherwise, don't see the un-minified version live yet so can't test that.

**Comment by tobscure** [comment]
Ohhh I forgot about them. The exception is if System.import is called for a module that's already loaded, which all of those ones should be. Nevertheless, they should be using System.get. I've updated it on the dev forum – does it work now?

**Comment by wizgriz** [comment]
Yep, working.

**Comment by tobscure** [comment]
For the record, I was wrong – System.import will always try to make a Promise. I guess most browsers must have native Promises implemented by now, but obviously not Pale Moon...
