### ISSUE TITLE
Can't delete tags

### ISSUE THREAD

**Issue by Petrouchka** [flarum/core#342]
I can't delete tags, I've got the message "Oops! Something went wrong on the server. Please reload the page and try again."

**Comment by Felli** [comment]
Try importing fresh files, this temporarily fixes some of the problems that I've been having.

**Comment by mhsabbagh** [comment]
Hello.. I've the same problem here.
Any fix for that?

**Comment by franzliedke** [comment]
There will be, please be patient. :)

**Comment by mhsabbagh** [comment]
Hello.

Is there any thing new about this bug? I am sorry to be so much "annoying", but the script is totally not usable because of this bug, I can't remove tags, I can't rename them, I can't modify them at all. Everything would be perfect if this one is just fixed :smile: 

Any help would be appreciated.

**Comment by Felli** [comment]
@mhsabbagh From what I can tell in beta 2 this was fixed.

**Comment by mhsabbagh** [comment]
@Felli Nope, I just tried the new beta and the bug stills there, at least for me.

**Comment by mhsabbagh** [comment]
I've used the instructions at http://flarum.org/docs/troubleshooting/ to see what's going on, and I discovered that the delete button (for example) does nothing, the request is empty.

This is the header of the request:
DELETE /api/tags/1 HTTP/1.1
Host: xxxxxxxxxxx.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: ar,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Authorization: Token xxxxxxxxxxxxxxxxxxxxZrGvdZMl1aPHUCjVEpES7
Referer: http://xxxxxxxxxxxx.com/admin
Content-Length: 0
Content-Type: text/plain; charset=UTF-8
Cookie: hauid=xxxxxxxxxxxxxxxxxxxvn6l6kaipszr8b; flarum_remember=xxIO7xxxxxxxxxxxxxxxxxxxxxrGvdZMl1aPHUCjVEpExx
Connection: keep-alive

The request itself is empty.

**Comment by tobscure** [comment]
That's the request... What about the response?

**Comment by mhsabbagh** [comment]
@tobscure Nothing, there is no response.

**Comment by tobscure** [comment]
There should at least be response headers, with a status code? No response doesn't make any sense.

**Comment by mhsabbagh** [comment]
Well, that what should have happened, but as you can see from the screenshot, there is nothing.
![screenshot from 2015-10-29 07 41 46](https://cloud.githubusercontent.com/assets/1293003/10810301/220f3838-7e08-11e5-9b9a-f1efcab7497f.png)

**Comment by tobscure** [comment]
What about under the "Headers" tab?

**Comment by mhsabbagh** [comment]
Those are the request headers, the ones that I already sent.

**Comment by franzliedke** [comment]
No, there should be response headers, too, under the "Headers" tab.

**Comment by mhsabbagh** [comment]
Ah now I found them after I repeated the test again, Here is what I found:

Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html; charset=UTF-8
Date: Thu, 29 Oct 2015 09:16:49 GMT
Server: nginx
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-Frame-Options: SAMEORIGIN
X-Powered-By: PHP/5.6.14

**Comment by franzliedke** [comment]
Hmm, is this still happening?
