### ISSUE TITLE
Beta 2 to 4 upgraded, text not displaying, only variable names

### ISSUE THREAD

**Issue by brijam** [flarum/core#671]
After upgrading from beta2 to beta4 I'm having the same issue as reported here:
https://discuss.flarum.org/d/1340-weird-language-phrases-in-beta3/3
and here
https://discuss.flarum.org/d/1351-not-loading-labels/7

I did the database action as requested, but the result leads me to believe nothing was changed:
```bash
mysql> UPDATE `settings` SET `value` = 'en' WHERE `key` = 'default_locale';
Query OK, 0 rows affected (0.00 sec)
Rows matched: 1  Changed: 0  Warnings: 0
```

After that I confirmed that English extension was enabled, deleted assets/*.js and the issue is still there.

**Comment by Luceos** [comment]
Is the English extension visible in the admin area under extensions and can you enable/re-enable it?

Also, because the query did nothing, what is the value of `default_locale` in the settings table?

**Comment by brijam** [comment]
Yes, the English extension is visible and enabling/disabling/enabling doesn't have an effect.
The value is en:
mysql> select * from config;
+--------------------------------+---------------------------------------------------------------------------------------------------+
| key                            | value                                                                                             |
+--------------------------------+---------------------------------------------------------------------------------------------------+
| allow_post_editing             | -1                                                                                                |
| allow_renaming                 | 10                                                                                                |
| allow_sign_up                  | 1                                                                                                 |
| custom_less                    |                                                                                                   |
| default_locale                 | en                                                                                                |

**Comment by tobscure** [comment]
Delete assets/*.js

**Comment by brijam** [comment]
Ok I did the entire thing again, this time it worked.  :)

**Comment by brijam** [comment]
Okay, it worked for a minute, now it's throwing interesting bugs:
```bash
15. Flarum\Core\Exception\PermissionDeniedException
…/­vendor/­flarum/­core/­src/­Admin/­Middleware/­RequireAdministrateAbility.php43
14. Flarum\Admin\Middleware\RequireAdministrateAbility __invoke
<#unknown>0
13. call_user_func
…/­vendor/­zendframework/­zend-stratigility/­src/­Dispatch.php81
12. Zend\Stratigility\Dispatch __invoke
…/­vendor/­zendframework/­zend-stratigility/­src/­Next.php113
11. Zend\Stratigility\Next __invoke
…/­vendor/­flarum/­core/­src/­Http/­Middleware/­ParseJsonBody.php30
10. Flarum\Http\Middleware\ParseJsonBody __invoke
<#unknown>0
9. call_user_func
…/­vendor/­zendframework/­zend-stratigility/­src/­Dispatch.php81
8. Zend\Stratigility\Dispatch __invoke
…/­vendor/­zendframework/­zend-stratigility/­src/­Next.php113
7. Zend\Stratigility\Next __invoke
…/­vendor/­flarum/­core/­src/­Http/­Middleware/­AuthenticateWithCookie.php42
6. Flarum\Http\Middleware\AuthenticateWithCookie __invoke
<#unknown>0
5. call_user_func
…/­vendor/­zendframework/­zend-stratigility/­src/­Dispatch.php81
4. Zend\Stratigility\Dispatch __invoke
…/­vendor/­zendframework/­zend-stratigility/­src/­Next.php113
3. Zend\Stratigility\Next __invoke
…/­vendor/­zendframework/­zend-stratigility/­src/­MiddlewarePipe.php75
2. Zend\Stratigility\MiddlewarePipe __invoke
…/­vendor/­zendframework/­zend-diactoros/­src/­Server.php166
1. Zend\Diactoros\Server listen
…/­vendor/­flarum/­core/­src/­Http/­AbstractServer.php33
0. Flarum\Http\AbstractServer listen
…/­admin.php16
```

**Comment by brijam** [comment]
![flarum-issue](https://cloud.githubusercontent.com/assets/280565/11789497/a0958bfa-a24b-11e5-947f-8e66ffc4f98f.png)

**Comment by Luceos** [comment]
How did you update? It seems you are on the dev branch, can you post your composer.lock file?

**Comment by brijam** [comment]
Here's what I did to update:
```bash
php ../../composer.phar create-project flarum/flarum . --stability=beta
```
Attached is my composer.lock in a .zip file.
[composer.zip](https://github.com/flarum/core/files/61586/composer.zip)

**Comment by brijam** [comment]
Is there anything else I can try?

**Comment by Luceos** [comment]
Nope, have patience.

**Comment by franzliedke** [comment]
@brijam What's the exception message on the screen that you [posted above](https://github.com/flarum/core/issues/671#issuecomment-164515068)?

**Comment by brijam** [comment]
Flarum\Core\Exception\PermissionDeniedException
.../vendor/flarum/core/src/Admin/Middleware/RequireAdministrateAbility.php:43

**Comment by brijam** [comment]
Maybe these are a little more helpful?

![flarum-issue1](https://cloud.githubusercontent.com/assets/280565/11905802/2e886b24-a57d-11e5-90e3-0eee00fdad16.png)

![flarum-issue2](https://cloud.githubusercontent.com/assets/280565/11905805/34a31b1c-a57d-11e5-8f83-c4546171420d.png)

**Comment by tobscure** [comment]
I think this should be fixed in dev-master

**Comment by brijam** [comment]
I tried from scratch and am still experiencing the issue.  Here's some more information: Apache log says this:
[Mon Jan 18 16:18:57.077726 2016] [:error] [pid 5123] [client 108.162.245.14:59021] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/storage/views/a5b3f9fda29328c2d9418b8291b3ca19 on line 8, referer: http://forums.jmpdrv.com/

That a5b3...ca19 file contains this:
<?php
$url = app('Flarum\Forum\UrlGenerator');
?>
<div class="container">
    <h2><?php echo e($translator->trans('core.ref.all_discussions')); ?></h2>

    <ul>
        <?php foreach($document->data as $discussion): ?>
            <li>
                <a href="<?php echo e($url->toRoute('discussion', [
                    'id' => $discussion->id . '-' . $discussion->attributes->title
                ])); ?>">
                    <?php echo e($discussion->attributes->title); ?>

                </a>
            </li>
        <?php endforeach; ?>
    </ul>

    <a href="<?php echo e($url->toRoute('index')); ?>?page=<?php echo e($page + 1); ?>"><?php echo e($translator->trans('core.basic.next_page_button')); ?> &raquo;</a>
</div>

**Comment by brijam** [comment]
Unfortunately I'm still seeing this.  I followed the instructions for a beta2 - beta4 upgrade.  Logged in as Admin looks great, although I am seeing an 'oops' error with notifications everything else appears to work.  The problem occurs when I browse to the site not logged in.

Apache's error log has many lines of this error:
[Mon Jan 18 16:18:57.077726 2016] [:error] [pid 5123] [client 108.162.245.14:59021] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/storage/views/a5b3f9fda29328c2d9418b8291b3ca19 on line 8, referer: http://forums.jmpdrv.com/

Line 8 of that a5b...ca19 contains this:
        <?php foreach($document->data as $discussion): ?>

**Comment by brijam** [comment]
This was the debug on the Admin notification errors:
Welcome to the XO Forum
The official forum for XO, the upcoming sci-fi strategy game from Jumpdrive Studios.

        All Discussions
        Following
        Tags
        Announcements
        Discussion
        Off Topic
        Meta

[Pre-Alpha] What feature would you like to see in XO?

    Discussion
    brijam replied 3 days ago 

14
J

I see you're using Flarum!

    Meta
    brijam replied 3 days ago 

2

Anybody watching The Expanse?

    Off Topic
    brijam replied 3 days ago 

5

End of the year update

    Announcements
    JMPDRV started 18 days ago
    It’s hard to believe that XO has been in development for over an entire year now. At the beginning of 2015, a small group of strangers got together in a closet (which we lovingly refer to as an “offic...

0

[Off-Topic] Ask Jumpdrive Studios!

    Off Topic
    chairliketeeth replied Dec '15 

7

Formatting in the Forums

    Meta
    thelazyone22 replied Dec '15 

4

End of the year update on XO - coming soon!

    Announcements
    chairliketeeth started Dec '15 

1

[Off-Topic] What are you looking to buy / receive this holiday 2015?

    Off Topic
    thelazyone22 replied Nov '15 

2

The Official XO forum is live!

    Announcements
    chairliketeeth replied Nov '15 

11

Time-Sensitive Edits?

    Meta
    chairliketeeth replied Nov '15 

7

Steam Controller

    Discussion
    chairliketeeth replied Nov '15 

3

Whatcha playin?

    Off Topic
    thelazyone22 replied Nov '15 

3

What got you to back?

    Off Topic
    thelazyone22 replied Nov '15 

11

Science Fiction Warfare - strategies and tactics

    Off Topic
    Gahbryel replied Nov '15 

5
J

General Discussion / Introduce Yourself

    Discussion
    Gahbryel replied Nov '15 

20

Sign Up problems? Read this...

    Meta
    brijam started Nov '15
    This is beta forum software so, like XO, it isn't finished. At the moment there are no error messages, so if you are having trouble signing up:   Your password has to be at least eight characters   ...

0

New XO t-shirts are up for sale on the shop

    Discussion
    Adam replied Nov '15 

1

XO Development update on Twitch: October

    Discussion
    chairliketeeth started Nov '15 

1

    A
    Pre-order options
        Discussion
        chairliketeeth replied Nov '15 1

500 Internal Server Error

GET http://forums.jmpdrv.com/api/notifications

{
  "errors": [
    {
      "code": 500,
      "title": "Internal server error",
      "detail": "exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'notifications_read_time' in 'field list'' in /var/www/html/vendor/illuminate/database/Connection.php:411\nStack trace:\n#0 /var/www/html/vendor/illuminate/database/Connection.php(411): PDO->prepare('update `users` ...')\n#1 /var/www/html/vendor/illuminate/database/Connection.php(644): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}(Object(Illuminate\\Database\\MySqlConnection), 'update `users` ...', Array)\n#2 /var/www/html/vendor/illuminate/database/Connection.php(611): Illuminate\\Database\\Connection->runQueryCallback('update `users` ...', Array, Object(Closure))\n#3 /var/www/html/vendor/illuminate/database/Connection.php(416): Illuminate\\Database\\Connection->run('update `users` ...', Array, Object(Closure))\n#4 /var/www/html/vendor/illuminate/database/Connection.php(359): Illuminate\\Database\\Connection->affectingStatement('update `users` ...', Array)\n#5 /var/www/html/vendor/illuminate/database/Query/Builder.php(1842): Illuminate\\Database\\Connection->update('update `users` ...', Array)\n#6 /var/www/html/vendor/illuminate/database/Eloquent/Builder.php(318): Illuminate\\Database\\Query\\Builder->update(Array)\n#7 /var/www/html/vendor/illuminate/database/Eloquent/Model.php(1588): Illuminate\\Database\\Eloquent\\Builder->update(Array)\n#8 /var/www/html/vendor/illuminate/database/Eloquent/Model.php(1507): Illuminate\\Database\\Eloquent\\Model->performUpdate(Object(Illuminate\\Database\\Eloquent\\Builder), Array)\n#9 /var/www/html/vendor/flarum/core/src/Api/Controller/ListNotificationsController.php(63): Illuminate\\Database\\Eloquent\\Model->save()\n#10 /var/www/html/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(96): Flarum\\Api\\Controller\\ListNotificationsController->data(Object(Zend\\Stratigility\\Http\\Request), Object(Tobscure\\JsonApi\\Document))\n#11 /var/www/html/vendor/flarum/core/src/Http/GenerateRouteHandlerTrait.php(35): Flarum\\Api\\Controller\\AbstractSerializeController->handle(Object(Zend\\Stratigility\\Http\\Request))\n#12 /var/www/html/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(67): Flarum\\Api\\ApiServiceProvider->Flarum\\Http\\{closure}(Object(Zend\\Stratigility\\Http\\Request), Array)\n#13 [internal function]: Flarum\\Http\\Middleware\\DispatchRoute->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#14 /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php(81): call_user_func(Object(Flarum\\Http\\Middleware\\DispatchRoute), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#15 /var/www/html/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#16 /var/www/html/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(32): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#17 [internal function]: Flarum\\Api\\Middleware\\FakeHttpMethods->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#18 /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php(81): call_user_func(Object(Flarum\\Api\\Middleware\\FakeHttpMethods), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#19 /var/www/html/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#20 /var/www/html/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(30): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#21 [internal function]: Flarum\\Http\\Middleware\\ParseJsonBody->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#22 /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php(81): call_user_func(Object(Flarum\\Http\\Middleware\\ParseJsonBody), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#23 /var/www/html/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#24 /var/www/html/vendor/flarum/core/src/Api/Middleware/AuthenticateWithHeader.php(50): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#25 [internal function]: Flarum\\Api\\Middleware\\AuthenticateWithHeader->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#26 /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php(81): call_user_func(Object(Flarum\\Api\\Middleware\\AuthenticateWithHeader), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#27 /var/www/html/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#28 /var/www/html/vendor/flarum/core/src/Http/Middleware/AuthenticateWithCookie.php(42): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#29 [internal function]: Flarum\\Http\\Middleware\\AuthenticateWithCookie->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#30 /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php(81): call_user_func(Object(Flarum\\Http\\Middleware\\AuthenticateWithCookie), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#31 /var/www/html/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#32 /var/www/html/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(75): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#33 /var/www/html/vendor/zendframework/zend-diactoros/src/Server.php(166): Zend\\Stratigility\\MiddlewarePipe->__invoke(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Diactoros\\Response), NULL)\n#34 /var/www/html/vendor/flarum/core/src/Http/AbstractServer.php(33): Zend\\Diactoros\\Server->listen()\n#35 /var/www/html/api.php(16): Flarum\\Http\\AbstractServer->listen()\n#36 {main}\n\nNext exception 'Illuminate\\Database\\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'notifications_read_time' in 'field list' (SQL: update `users` set `notifications_read_time` = 2016-01-19 00:14:56 where `id` = 1)' in /var/www/html/vendor/illuminate/database/Connection.php:651\nStack trace:\n#0 /var/www/html/vendor/illuminate/database/Connection.php(611): Illuminate\\Database\\Connection->runQueryCallback('update `users` ...', Array, Object(Closure))\n#1 /var/www/html/vendor/illuminate/database/Connection.php(416): Illuminate\\Database\\Connection->run('update `users` ...', Array, Object(Closure))\n#2 /var/www/html/vendor/illuminate/database/Connection.php(359): Illuminate\\Database\\Connection->affectingStatement('update `users` ...', Array)\n#3 /var/www/html/vendor/illuminate/database/Query/Builder.php(1842): Illuminate\\Database\\Connection->update('update `users` ...', Array)\n#4 /var/www/html/vendor/illuminate/database/Eloquent/Builder.php(318): Illuminate\\Database\\Query\\Builder->update(Array)\n#5 /var/www/html/vendor/illuminate/database/Eloquent/Model.php(1588): Illuminate\\Database\\Eloquent\\Builder->update(Array)\n#6 /var/www/html/vendor/illuminate/database/Eloquent/Model.php(1507): Illuminate\\Database\\Eloquent\\Model->performUpdate(Object(Illuminate\\Database\\Eloquent\\Builder), Array)\n#7 /var/www/html/vendor/flarum/core/src/Api/Controller/ListNotificationsController.php(63): Illuminate\\Database\\Eloquent\\Model->save()\n#8 /var/www/html/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(96): Flarum\\Api\\Controller\\ListNotificationsController->data(Object(Zend\\Stratigility\\Http\\Request), Object(Tobscure\\JsonApi\\Document))\n#9 /var/www/html/vendor/flarum/core/src/Http/GenerateRouteHandlerTrait.php(35): Flarum\\Api\\Controller\\AbstractSerializeController->handle(Object(Zend\\Stratigility\\Http\\Request))\n#10 /var/www/html/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(67): Flarum\\Api\\ApiServiceProvider->Flarum\\Http\\{closure}(Object(Zend\\Stratigility\\Http\\Request), Array)\n#11 [internal function]: Flarum\\Http\\Middleware\\DispatchRoute->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#12 /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php(81): call_user_func(Object(Flarum\\Http\\Middleware\\DispatchRoute), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#13 /var/www/html/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#14 /var/www/html/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(32): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#15 [internal function]: Flarum\\Api\\Middleware\\FakeHttpMethods->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#16 /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php(81): call_user_func(Object(Flarum\\Api\\Middleware\\FakeHttpMethods), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#17 /var/www/html/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#18 /var/www/html/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(30): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#19 [internal function]: Flarum\\Http\\Middleware\\ParseJsonBody->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#20 /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php(81): call_user_func(Object(Flarum\\Http\\Middleware\\ParseJsonBody), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#21 /var/www/html/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#22 /var/www/html/vendor/flarum/core/src/Api/Middleware/AuthenticateWithHeader.php(50): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#23 [internal function]: Flarum\\Api\\Middleware\\AuthenticateWithHeader->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#24 /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php(81): call_user_func(Object(Flarum\\Api\\Middleware\\AuthenticateWithHeader), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#25 /var/www/html/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#26 /var/www/html/vendor/flarum/core/src/Http/Middleware/AuthenticateWithCookie.php(42): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#27 [internal function]: Flarum\\Http\\Middleware\\AuthenticateWithCookie->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#28 /var/www/html/vendor/zendframework/zend-stratigility/src/Dispatch.php(81): call_user_func(Object(Flarum\\Http\\Middleware\\AuthenticateWithCookie), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#29 /var/www/html/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#30 /var/www/html/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(75): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#31 /var/www/html/vendor/zendframework/zend-diactoros/src/Server.php(166): Zend\\Stratigility\\MiddlewarePipe->__invoke(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Diactoros\\Response), NULL)\n#32 /var/www/html/vendor/flarum/core/src/Http/AbstractServer.php(33): Zend\\Diactoros\\Server->listen()\n#33 /var/www/html/api.php(16): Flarum\\Http\\AbstractServer->listen()\n#34 {main}"
    }
  ]
}

**Comment by Luceos** [comment]
You're missing a migration. The `notifications_read_time` in the `users` table was migrated:

https://github.com/flarum/core/blob/master/migrations/2015_09_22_030432_rename_notification_read_time.php

Check the users table and manually rename `notification_read_time` to `notifications_read_time`

**Comment by brijam** [comment]
My mysql skills aren't super hot, but I tried this and still have the same problem:
<code>
mysql> ALTER TABLE `users` CHANGE COLUMN `notification_read_time` `notifications_read_time` VARCHAR(255) NOT NULL;
Query OK, 76 rows affected, 62 warnings (0.05 sec)
Records: 76  Duplicates: 0  Warnings: 62

mysql> quit;
</code>
</code>
mysql> select * from users;                
+----+-----------------+------------------------------+--------------+--------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------+---------------------+-------------------------+-------------------+----------------+---------------+------------+
| id | username        | email                        | is_activated | password                                                     | bio                                                                                                                                                                                 | avatar_path          | preferences                                                                                                                                                                                                                                                                                                                                                                                                  | join_time           | last_seen_time      | read_time           | notifications_read_time | discussions_count | comments_count | suspend_until | twitter_id |
</code>

**Comment by Luceos** [comment]
You might have the same 500 int server error; but you can't have the same pdo exception; impossible :D
