### ISSUE TITLE
[Mentions] Use URL generator for mention links correctly

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#777]
See https://github.com/s9e/TextFormatter/issues/23#issuecomment-168054405.

(taken from https://github.com/flarum/flarum-ext-mentions/pull/11#issuecomment-180912062)

**Comment by luceos** [comment]
Fixed in https://github.com/flarum/mentions/commit/4b34e5096d1a2cef127b41756ebd7b4eb46bb0dd

**Comment by franzliedke** [comment]
As far as I can tell, this is not yet fixed.

As this rabbit-hole is quite deep, I've updated the issue description with a more direct link to what we need to build.
