### ISSUE TITLE
Extension icon show no more

### ISSUE THREAD

**Issue by sijad** [flarum/core#803]
Hi, I noticed extension with custom icon (the ones which don't use font-awesome icons) showing without icon
I see this with inspect tool
```
<span class="ExtensionListItem-icon ExtensionIcon" style="color: #fff; background-color: #5E8E14; background-size: cover;"><i class="icon fa fa-fw fa-undefined"></i></span>
```
**fa-undefined** is interesting...

**Comment by Luceos** [comment]
Probably related to #799

**Comment by Luceos** [comment]
Please recompile the js for admin (and forum) after downloading latest dev-master.

**Comment by Luceos** [comment]
Fixed in: https://github.com/flarum/core/pull/801

**Comment by sijad** [comment]
I've tryed latest version but still can't see extension Icons...
